name: Develop Build

on:
  push:
    branches:
      - "develop"
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: lint
        run: make lint