name: Develop Build

on:
  push:
    branches:
      - "develop"
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build develop
        run: ./gradlew assembleDebug
      - name: distribute develop
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
          -F "message=${{ github.event.head_commit.url }}" \
          -F "distribution_name=develop" \
          "https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/apps"