name: Release Build

on:
  push:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: Permission Gradle
        run: chmod 777 ./gradlew
      - name: Build release
        run: ./gradlew build
      - name: distribute release
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@app/build/outputs/apk/debug/app-release-unsigned.apk" \
          -F "message=${{ github.event.head_commit.url }}" \
          -F "distribution_name=release" \
          "https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/apps"